name: 'dbt_shanghai_hackathon'
version: '1.0.0'
config-version: 2

profile: 'dbt_shanghai_hackathon'

models:
  dbt_shanghai_hackathon:
    +materialized: table
    +file_format: parquet

    events:
      +schema: events
    
    properties:
      +schema: properties

    property_materials:
      +materialized: view
      +schema: property_materials

    index:
      +materialized: view
      +schema: index

seeds:
  dbt_shanghai_hackathon:
    +materialized: table
    +file_format: parquet

    phishing:
      +schema: property_materials
