
name: 'dbt_shanghai_hackathon'
version: '1.0.0'
config-version: 2

profile: 'dbt_shanghai_hackathon'

models:
  dbt_shanghai_hackathon:
    events:
      +materialized: table
      +file_format: parquet
      +schema: events

    label_materials:
      +materialized: view
      +schema: label_materials

    labels:
      +materialized: table
      +file_format: parquet
      +schema: labels

    index:
      +materialized: view
      +schema: index
