version: 2

models:
  - name: nft_whale
  - name: smart_nft_trader
  - name: opensea_trader
  - name: blue_chip_holder
  - name: ens_name
  - name: ens_name_reverse
  - name: uncommon_nft_trader
  - name: rare_nft_trader
  - name: epic_nft_trader
  - name: legendary_nft_trader
  - name: diversified_nft_holder